### ISSUE TITLE
Error on examples

### ISSUE THREAD

**Issue by mhbw** [jaebradley/draftkings_client#36]
first example is erroring out

    from draft_kings.client import contests, Sport

    contests(sport=Sport.nba)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ImportError: cannot import name 'Sport' from 'draft_kings.client'     (/anaconda3/lib/python3.7/site-packages/draft_kings/client.py)

**Comment by mhbw** [comment]
I think this is mostly documentation error, because some other parts were erroring as well.

I first ran 

    from draft_kings import Sport

which worked but the suggested calls of Sport.nba failed

    >>> contests(sport=Sport.nba)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/anaconda3/lib/python3.7/enum.py", line 348, in __getattr__
        raise AttributeError(name) from None
    AttributeError: nba
    >>> contests(sport=Sport.nhl)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/anaconda3/lib/python3.7/enum.py", line 348, in __getattr__
        raise AttributeError(name) from None
   AttributeError: nhl

this worked
   contests(sport=Sport.NHL)

**Comment by jaebradley** [comment]
@mhbw Thanks for reporting this issue and sorry you were running into issues. These were documentation errors - hopefully [commit `ba76a`](https://github.com/jaebradley/draftkings_client/commit/ba76a97fdee412974f885acf471ede7c0f1935e1) has fixed the `Sport` enum example in the README.

**Comment by AccidentalGuru** [comment]
I have that issue on Jupyter, but it works fine on IDLE. Dunno if that helps or not.

**Comment by jaebradley** [comment]
@mhbw and @AccidentalGuru I think there was a documentation issue - instead of `from draft_kings import Sport` it should be `from draft_kings.data import Sport`.

I updated this documentation in https://github.com/jaebradley/draftkings_client/commit/5cf50900947d5b54a82a4ddadd98673721386a18.

When I use `repl.it` this is what I see

![image](https://user-images.githubusercontent.com/8136030/61264525-c5843700-a741-11e9-8dd8-aca81a3335c7.png)

https://repl.it/@jaebradley/draftkingsv201

**Comment by mhbw** [comment]
worked! thanks.
